# Generated by Django 4.0.4 on 2022-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.PositiveIntegerField(auto_created=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('manufacturer', models.CharField(max_length=200)),
                ('modelDate', models.DateField()),
                ('mileage_km', models.PositiveIntegerField()),
                ('displacement_cc', models.PositiveBigIntegerField(max_length=1000)),
                ('condition', models.PositiveSmallIntegerField(max_length=10)),
            ],
        ),
    ]
