# Generated by Django 4.0.4 on 2022-06-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_vehicle_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
    ]
