# Generated by Django 4.0.4 on 2022-06-11 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='displacement_cc',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.vehicle')),
            ],
        ),
    ]
