# Generated by Django 4.0.4 on 2022-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_vehicle_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='modelDate',
            field=models.CharField(max_length=4),
        ),
    ]
