# Generated by Django 4.0.4 on 2022-06-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_vehicle_condition_alter_vehicle_modeldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
