# Generated by Django 4.0.4 on 2022-06-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(default='Invalid Description', max_length=200),
            preserve_default=False,
        ),
    ]
